apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: zenvy
spec:
  replicas: 2 # run 2 replicas for high availability
  selector:
    matchLabels:
      app: zenvy-server
  template:
    metadata:
      labels:
        app: zenvy-server
    spec:
      containers:
        - name: zenvy-server
          image: iamsymon/mini-ecommerce-platform-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: zenvy-server-secret
          resources:
            requests:
              cpu: "100m" # Request 0.1 CPU core
              memory: "128Mi" # Request 128 MB of memory
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe: # Is the app alive?
            httpGet:
              path: /api/products # Use a simple, fast endpoint
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe: # Is the app ready to receive traffic?
            httpGet:
              path: /api/products
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: zenvy
spec:
  selector:
    app: zenvy-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
